# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    container_name: mongo_database
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Ashish123
      ME_CONFIG_MONGODB_URL: mongodb://root:Ashish123@mongo:27017/
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    # ports:
    #   - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: Ashish123
      # ME_CONFIG_MONGODB_URL: mongodb://root:Ashish123@mongo:27017/